name: 'Setup Python Environment'
description: 'Set up Python and install dependencies'
inputs:
  python_version:
    description: 'Python version to set up'
    required: false
    default: "3.10"
  extras:
    description: 'extra deps: poetry install -E whatever'
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Install poetry
      shell: bash
      run: pip install --upgrade pip poetry

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'poetry'
        cache-dependency-path: '**/poetry.lock'

    - name: Install dependencies
      shell: bash
      run: |
        poetry config virtualenvs.in-project true
        poetry install --no-interaction --no-ansi ${{ inputs.extras }}

    - name: Add virtualenv to PATH
      shell: bash
      run: |
        echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> "$GITHUB_ENV"
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "$GITHUB_WORKSPACE/.venv/Scripts" >> "$GITHUB_PATH"
        else
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
        fi
