name: 'Setup Python Environment'
description: 'Set up Python and install dependencies'
inputs:
  python_version:
    description: 'Python version to set up'
    required: false
    default: "3.10"
  extras:
    description: 'extra deps: poetry install -E whatever'
    required: false
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'poetry'

    # - name: Setup cache for poetry
    #   uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
    #   with:
    #     path: |
    #       ~/.cache/pypoetry/cache
    #     key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-${{ inputs.python_version }}-${{ inputs.extras }}

    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction --no-ansi ${{ inputs.extras }}
    - shell: bash
      run: eval $(poetry env activate)
        # python -m pip install --upgrade pip poetry
        # poetry config virtualenvs.create false
