# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      # 1. Dependencies like sphinx/-theme are in the 'dev' dependency group
      # 2. As of poetry>1.8 we need to set VIRTUAL_ENV: https://github.com/python-poetry/poetry/issues/9025
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with dev --no-root

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
