---
coverage:
  precision: 2
  round: down
  range: 95...100

  status:
    project:
      default:
        target: auto
        threshold: 0.25%
        base: auto
    patch: false
    changes: false

comment:
  layout: header, diff, files
  behavior: default

codecov:
  notify:
    require_ci_to_pass: false
    after_n_builds: 1  # send notifications and complete cc build after 1 upload
