# The headings dictionary is used to provide custom section titles for the API methods documentation. The keys should be in the format "AsyncCogniteClient.<any nested accessors if applicable>.<method_name>" and the values should be the desired section title for that method in the generated documentation.
# If not provided, the section title will default to the method name without underscores and capitalized (i.e., the part after the last dot in the key).

headings = {
    "AsyncCogniteClient.iam.compare_capabilities": "Compare capabilities",
    "AsyncCogniteClient.iam.verify_capabilities": "Verify my capabilities",
    "AsyncCogniteClient.iam.principals.list": "List principals",
    "AsyncCogniteClient.iam.principals.me": "Get the current caller’s principal",  # noqa: RUF001
    "AsyncCogniteClient.iam.principals.retrieve": "Retrieve a principal",
    "AsyncCogniteClient.iam.token.inspect": "Inspect the token currently used by the client",
    "AsyncCogniteClient.iam.groups.create": "Create groups",
    "AsyncCogniteClient.iam.groups.delete": "Delete groups",
    "AsyncCogniteClient.iam.groups.list": "List groups",
    "AsyncCogniteClient.iam.security_categories.create": "Create security categories",
    "AsyncCogniteClient.iam.security_categories.delete": "Delete security categories",
    "AsyncCogniteClient.iam.security_categories.list": "List security categories",
    "AsyncCogniteClient.iam.sessions.create": "Create a session",
    "AsyncCogniteClient.iam.sessions.list": "List sessions",
    "AsyncCogniteClient.iam.sessions.retrieve": "Retrieve a session",
    "AsyncCogniteClient.iam.sessions.revoke": "Revoke a session",
    "AsyncCogniteClient.iam.user_profiles.disable": "Disable user profiles for project",
    "AsyncCogniteClient.iam.user_profiles.enable": "Enable user profiles for project",
    "AsyncCogniteClient.iam.user_profiles.list": "List user profiles",
    "AsyncCogniteClient.iam.user_profiles.me": "Get my own user profile",
    "AsyncCogniteClient.iam.user_profiles.retrieve": "Retrieve one or more user profiles",
    "AsyncCogniteClient.iam.user_profiles.search": "Search for user profiles",
    "AsyncCogniteClient.data_modeling.data_models.apply": "Apply data models",
    "AsyncCogniteClient.data_modeling.data_models.delete": "Delete data models",
    "AsyncCogniteClient.data_modeling.data_models.list": "List data models",
    "AsyncCogniteClient.data_modeling.data_models.retrieve": "Retrieve data models by id(s)",
    "AsyncCogniteClient.data_modeling.spaces.apply": "Apply spaces",
    "AsyncCogniteClient.data_modeling.spaces.delete": "Delete spaces",
    "AsyncCogniteClient.data_modeling.spaces.list": "List spaces",
    "AsyncCogniteClient.data_modeling.spaces.retrieve": "Retrieve a space by id",
    "AsyncCogniteClient.data_modeling.views.apply": "Apply views",
    "AsyncCogniteClient.data_modeling.views.delete": "Delete views",
    "AsyncCogniteClient.data_modeling.views.list": "List views",
    "AsyncCogniteClient.data_modeling.views.retrieve": "Retrieve views by id(s)",
    "AsyncCogniteClient.data_modeling.containers.apply": "Apply containers",
    "AsyncCogniteClient.data_modeling.containers.delete": "Delete containers",
    "AsyncCogniteClient.data_modeling.containers.delete_constraints": "Delete constraints",
    "AsyncCogniteClient.data_modeling.containers.delete_indexes": "Delete indexes",
    "AsyncCogniteClient.data_modeling.containers.list": "List containers",
    "AsyncCogniteClient.data_modeling.containers.retrieve": "Retrieve containers by id(s)",
    "AsyncCogniteClient.data_modeling.instances.aggregate": "Aggregate instances",
    "AsyncCogniteClient.data_modeling.instances.apply": "Apply instances",
    "AsyncCogniteClient.data_modeling.instances.delete": "Delete instances",
    "AsyncCogniteClient.data_modeling.instances.inspect": "Inspect instances",
    "AsyncCogniteClient.data_modeling.instances.list": "List instances",
    "AsyncCogniteClient.data_modeling.instances.query": "Query instances",
    "AsyncCogniteClient.data_modeling.instances.retrieve": "Retrieve instances by id(s)",
    "AsyncCogniteClient.data_modeling.instances.retrieve_edges": "Retrieve Edges by id(s)",
    "AsyncCogniteClient.data_modeling.instances.retrieve_nodes": "Retrieve Nodes by id(s)",
    "AsyncCogniteClient.data_modeling.instances.search": "Search instances",
    "AsyncCogniteClient.data_modeling.instances.sync": "Sync instances",
    "AsyncCogniteClient.data_modeling.statistics.project": "Project",
    "AsyncCogniteClient.data_modeling.statistics.spaces.list": "List space statistics",
    "AsyncCogniteClient.data_modeling.statistics.spaces.retrieve": "Retrieve space statistics",
    "AsyncCogniteClient.data_modeling.graphql.apply_dml": "Apply DML",
    "AsyncCogniteClient.data_modeling.graphql.query": "Execute GraphQl query",
    "AsyncCogniteClient.agents.chat": "Chat with an agent by external id",
    "AsyncCogniteClient.agents.delete": "Delete an agent by external id",
    "AsyncCogniteClient.agents.list": "List all agents",
    "AsyncCogniteClient.agents.retrieve": "Retrieve an agent by external id",
    "AsyncCogniteClient.agents.upsert": "Create or update an agent",
    "AsyncCogniteClient.ai.tools.documents.ask_question": "Document Question Answering",
    "AsyncCogniteClient.ai.tools.documents.summarize": "Document Summarization",
    "AsyncCogniteClient.assets.aggregate_cardinality_properties": "Aggregate Asset Property Cardinality",
    "AsyncCogniteClient.assets.aggregate_cardinality_values": "Aggregate Asset Value Cardinality",
    "AsyncCogniteClient.assets.aggregate_count": "Aggregate Asset Count",
    "AsyncCogniteClient.assets.aggregate_unique_properties": "Aggregate Asset Unique Properties",
    "AsyncCogniteClient.assets.aggregate_unique_values": "Aggregate Asset Unique Values",
    "AsyncCogniteClient.assets.create": "Create assets",
    "AsyncCogniteClient.assets.create_hierarchy": "Create asset hierarchy",
    "AsyncCogniteClient.assets.delete": "Delete assets",
    "AsyncCogniteClient.assets.list": "List assets",
    "AsyncCogniteClient.assets.retrieve": "Retrieve an asset by id",
    "AsyncCogniteClient.assets.retrieve_multiple": "Retrieve multiple assets by id",
    "AsyncCogniteClient.assets.retrieve_subtree": "Retrieve an asset subtree",
    "AsyncCogniteClient.assets.search": "Search for assets",
    "AsyncCogniteClient.assets.update": "Update assets",
    "AsyncCogniteClient.assets.upsert": "Upsert assets",
    "AsyncCogniteClient.events.aggregate_cardinality_properties": "Aggregate Event Property Cardinality",
    "AsyncCogniteClient.events.aggregate_cardinality_values": "Aggregate Event Values Cardinality",
    "AsyncCogniteClient.events.aggregate_count": "Aggregate Event Count",
    "AsyncCogniteClient.events.aggregate_unique_properties": "Aggregate Event Unique Properties",
    "AsyncCogniteClient.events.aggregate_unique_values": "Aggregate Event Unique Values",
    "AsyncCogniteClient.events.create": "Create events",
    "AsyncCogniteClient.events.delete": "Delete events",
    "AsyncCogniteClient.events.list": "List events",
    "AsyncCogniteClient.events.retrieve": "Retrieve an event by id",
    "AsyncCogniteClient.events.retrieve_multiple": "Retrieve multiple events by id",
    "AsyncCogniteClient.events.search": "Search for events",
    "AsyncCogniteClient.events.update": "Update events",
    "AsyncCogniteClient.events.upsert": "Upsert events",
    "AsyncCogniteClient.documents.aggregate_cardinality_properties": "Aggregate Document Count",
    "AsyncCogniteClient.documents.aggregate_cardinality_values": "Aggregate Document Value Cardinality",
    "AsyncCogniteClient.documents.aggregate_count": "Aggregate Document Count",
    "AsyncCogniteClient.documents.aggregate_unique_properties": "Aggregate Document Unique Properties",
    "AsyncCogniteClient.documents.aggregate_unique_values": "Aggregate Document Unique Values",
    "AsyncCogniteClient.documents.list": "List documents",
    "AsyncCogniteClient.documents.retrieve_content": "Retrieve Document Content",
    "AsyncCogniteClient.documents.retrieve_content_buffer": "Retrieve Document Content Buffer",
    "AsyncCogniteClient.documents.search": "Search Documents",
    "AsyncCogniteClient.documents.previews.download_document_as_pdf": "Download PDF Preview to Path",
    "AsyncCogniteClient.documents.previews.download_document_as_pdf_bytes": "Download PDF Preview Bytes",
    "AsyncCogniteClient.documents.previews.download_page_as_png": "Download Image Preview to Path",
    "AsyncCogniteClient.documents.previews.download_page_as_png_bytes": "Download Image Preview Bytes",
    "AsyncCogniteClient.documents.previews.retrieve_pdf_link": "Retrieve PDF Preview Temporary Link",
    "AsyncCogniteClient.files.aggregate_count": "Aggregate files metadata",
    "AsyncCogniteClient.files.retrieve": "Retrieve file metadata by id",
    "AsyncCogniteClient.files.retrieve_multiple": "Retrieve multiple files’ metadata by id",  # noqa: RUF001
    "AsyncCogniteClient.files.list": "List files metadata",
    "AsyncCogniteClient.files.search": "Search for files",
    "AsyncCogniteClient.files.create": "Create file metadata",
    "AsyncCogniteClient.files.upload": "Upload a file or directory",
    "AsyncCogniteClient.files.upload_bytes": "Upload a string or bytes",
    "AsyncCogniteClient.files.upload_content": "Upload a file content",
    "AsyncCogniteClient.files.upload_content_bytes": "Upload a file content in string or bytes",
    "AsyncCogniteClient.files.multipart_upload_session": "Upload a file in multiple parts",
    "AsyncCogniteClient.files.multipart_upload_content_session": "Upload a file content in multiple parts",
    "AsyncCogniteClient.time_series.aggregate_cardinality_properties": "Aggregate Time Series Property Cardinality",
    "AsyncCogniteClient.time_series.aggregate_cardinality_values": "Aggregate Time Series Values Cardinality",
    "AsyncCogniteClient.time_series.aggregate_count": "Aggregate Time Series Count",
    "AsyncCogniteClient.time_series.aggregate_unique_properties": "Aggregate Time Series Unique Properties",
    "AsyncCogniteClient.time_series.aggregate_unique_values": "Aggregate Time Series Unique Values",
    "AsyncCogniteClient.time_series.create": "Create time series",
    "AsyncCogniteClient.time_series.delete": "Delete time series",
    "AsyncCogniteClient.time_series.list": "List time series",
    "AsyncCogniteClient.time_series.retrieve": "Retrieve a time series by id",
    "AsyncCogniteClient.time_series.retrieve_multiple": "Retrieve multiple time series by id",
    "AsyncCogniteClient.time_series.search": "Search for time series",
    "AsyncCogniteClient.time_series.update": "Update time series",
    "AsyncCogniteClient.time_series.upsert": "Upsert time series",
    "AsyncCogniteClient.time_series.data.synthetic.query": "Calculate the result of a function on time series",
    "AsyncCogniteClient.time_series.data.delete_range": "Delete a range of datapoints",
    "AsyncCogniteClient.time_series.data.insert": "Insert datapoints",
    "AsyncCogniteClient.time_series.data.retrieve_arrays": "Retrieve datapoints as numpy arrays",
    "AsyncCogniteClient.time_series.data.retrieve": "Retrieve datapoints",
    "AsyncCogniteClient.time_series.data.retrieve_dataframe": "Retrieve datapoints in pandas dataframe",
    "AsyncCogniteClient.time_series.data.retrieve_latest": "Retrieve latest datapoint",
    "AsyncCogniteClient.time_series.data.insert_multiple": "Insert datapoints into multiple time series",
    "AsyncCogniteClient.time_series.data.delete_ranges": "Delete ranges of datapoints",
    "AsyncCogniteClient.time_series.data.insert_dataframe": "Insert pandas dataframe",
    "AsyncCogniteClient.time_series.data.__call__": "Iterate through datapoints in chunks",
    "AsyncCogniteClient.time_series.subscriptions.create": "Create datapoint subscriptions",
    "AsyncCogniteClient.time_series.subscriptions.delete": "Delete datapoint subscription",
    "AsyncCogniteClient.time_series.subscriptions.list": "List datapoint subscriptions",
    "AsyncCogniteClient.time_series.subscriptions.retrieve": "Retrieve a datapoint subscription by id(s)",
    "AsyncCogniteClient.time_series.subscriptions.update": "Update datapoint subscription",
    "AsyncCogniteClient.time_series.subscriptions.list_member_time_series": "List member time series of subscription",
    "AsyncCogniteClient.time_series.subscriptions.iterate_data": "Iterate over subscriptions data",
    "AsyncCogniteClient.sequences.aggregate_cardinality_properties": "Aggregate Sequences Property Cardinality",
    "AsyncCogniteClient.sequences.aggregate_cardinality_values": "Aggregate Sequences Value Cardinality",
    "AsyncCogniteClient.sequences.aggregate_count": "Aggregate Sequences Count",
    "AsyncCogniteClient.sequences.aggregate_unique_properties": "Aggregate Sequences Unique Properties",
    "AsyncCogniteClient.sequences.aggregate_unique_values": "Aggregate Sequences Unique Values",
    "AsyncCogniteClient.sequences.create": "Create a sequence",
    "AsyncCogniteClient.sequences.delete": "Delete sequences",
    "AsyncCogniteClient.sequences.list": "List sequences",
    "AsyncCogniteClient.sequences.retrieve": "Retrieve a sequence by id",
    "AsyncCogniteClient.sequences.retrieve_multiple": "Retrieve multiple sequences by id",
    "AsyncCogniteClient.sequences.search": "Search for sequences",
    "AsyncCogniteClient.sequences.update": "Update sequences",
    "AsyncCogniteClient.sequences.upsert": "Upsert sequences",
    "AsyncCogniteClient.sequences.data.delete": "Delete rows from a sequence",
    "AsyncCogniteClient.sequences.data.delete_range": "Delete a range of rows from a sequence",
    "AsyncCogniteClient.sequences.data.insert": "Insert rows into a sequence",
    "AsyncCogniteClient.sequences.data.insert_dataframe": "Insert a pandas dataframe into a sequence",
    "AsyncCogniteClient.sequences.data.retrieve": "Retrieve rows",
    "AsyncCogniteClient.sequences.data.retrieve_dataframe": "Retrieve rows in a pandas dataframe",
    "AsyncCogniteClient.sequences.data.retrieve_last_row": "Retrieve last row",
    "AsyncCogniteClient.three_d.models.create": "Create models",
    "AsyncCogniteClient.three_d.models.delete": "Delete models",
    "AsyncCogniteClient.three_d.models.list": "List models",
    "AsyncCogniteClient.three_d.models.retrieve": "Retrieve a model by ID",
    "AsyncCogniteClient.three_d.models.update": "Update models",
    "AsyncCogniteClient.three_d.revisions.create": "Create a revision",
    "AsyncCogniteClient.three_d.revisions.delete": "Delete revisions",
    "AsyncCogniteClient.three_d.revisions.filter_nodes": "Filter nodes",
    "AsyncCogniteClient.three_d.revisions.list": "List revisions",
    "AsyncCogniteClient.three_d.revisions.list_ancestor_nodes": "List ancestor nodes",
    "AsyncCogniteClient.three_d.revisions.list_nodes": "List nodes",
    "AsyncCogniteClient.three_d.revisions.retrieve": "Retrieve a revision by ID",
    "AsyncCogniteClient.three_d.revisions.update": "Update revisions",
    "AsyncCogniteClient.three_d.revisions.update_thumbnail": "Update a revision thumbnail",
    "AsyncCogniteClient.three_d.files.retrieve": "Retrieve a 3D file",
    "AsyncCogniteClient.three_d.asset_mappings.create": "Create an asset mapping",
    "AsyncCogniteClient.three_d.asset_mappings.delete": "Delete asset mappings",
    "AsyncCogniteClient.three_d.asset_mappings.list": "List asset mappings",
    "AsyncCogniteClient.entity_matching.delete": "Delete Entity Matching Models",
    "AsyncCogniteClient.entity_matching.fit": "Fit Entity Matching Model",
    "AsyncCogniteClient.entity_matching.list": "Retrieve Entity Matching Models",
    "AsyncCogniteClient.entity_matching.predict": "Predict Using an Entity Matching Model",
    "AsyncCogniteClient.entity_matching.refit": "Re-fit Entity Matching Model",
    "AsyncCogniteClient.entity_matching.retrieve": "Retrieve Entity Matching Models",
    "AsyncCogniteClient.entity_matching.retrieve_multiple": "Retrieve Entity Matching Models",
    "AsyncCogniteClient.entity_matching.update": "Update Entity Matching Models",
    "AsyncCogniteClient.diagrams.convert": "Convert to an interactive SVG where the provided annotations are highlighted",
    "AsyncCogniteClient.diagrams.detect": "Detect entities in Engineering Diagrams",
    "AsyncCogniteClient.vision.extract": "Extract",
    "AsyncCogniteClient.vision.get_extract_job": "Get vision extract job",
    "AsyncCogniteClient.raw.databases.create": "Create new databases",
    "AsyncCogniteClient.raw.databases.delete": "Delete databases",
    "AsyncCogniteClient.raw.databases.list": "List databases",
    "AsyncCogniteClient.raw.tables.create": "Create new tables in a database",
    "AsyncCogniteClient.raw.tables.delete": "Delete tables from a database",
    "AsyncCogniteClient.raw.tables.list": "List tables in a database",
    "AsyncCogniteClient.raw.rows.delete": "Delete rows from a table",
    "AsyncCogniteClient.raw.rows.insert": "Insert rows into a table",
    "AsyncCogniteClient.raw.rows.insert_dataframe": "Insert pandas dataframe",
    "AsyncCogniteClient.raw.rows.list": "List rows in a table",
    "AsyncCogniteClient.raw.rows.retrieve": "Get a row from a table",
    "AsyncCogniteClient.raw.rows.retrieve_dataframe": "Retrieve pandas dataframe",
    "AsyncCogniteClient.extraction_pipelines.create": "Create extraction pipeline",
    "AsyncCogniteClient.extraction_pipelines.delete": "Delete extraction pipelines",
    "AsyncCogniteClient.extraction_pipelines.list": "List extraction pipelines",
    "AsyncCogniteClient.extraction_pipelines.retrieve": "Retrieve an extraction pipeline by ID",
    "AsyncCogniteClient.extraction_pipelines.retrieve_multiple": "Retrieve multiple extraction pipelines by ID",
    "AsyncCogniteClient.extraction_pipelines.update": "Update extraction pipelines",
    "AsyncCogniteClient.extraction_pipelines.runs.create": "Report new runs",
    "AsyncCogniteClient.extraction_pipelines.runs.list": "List runs for an extraction pipeline",
    "AsyncCogniteClient.extraction_pipelines.config.create": "Create a config revision",
    "AsyncCogniteClient.extraction_pipelines.config.list": "List configuration revisions",
    "AsyncCogniteClient.extraction_pipelines.config.retrieve": "Get the latest or a specific config revision",
    "AsyncCogniteClient.extraction_pipelines.config.revert": "Revert to an earlier config revision",
    "AsyncCogniteClient.transformations.cancel": "Cancel transformation run by id",
    "AsyncCogniteClient.transformations.create": "Create transformations",
    "AsyncCogniteClient.transformations.list": "List transformations",
    "AsyncCogniteClient.transformations.preview": "Preview transformations",
    "AsyncCogniteClient.transformations.retrieve": "Retrieve transformations by id",
    "AsyncCogniteClient.transformations.retrieve_multiple": "Retrieve transformations by id",
    "AsyncCogniteClient.transformations.run": "Run transformations by id",
    "AsyncCogniteClient.transformations.update": "Update transformations",
    "AsyncCogniteClient.transformations.schedules.create": "Create transformation Schedules",
    "AsyncCogniteClient.transformations.schedules.delete": "Delete transformation schedules",
    "AsyncCogniteClient.transformations.schedules.list": "List transformation schedules",
    "AsyncCogniteClient.transformations.schedules.retrieve": "Retrieve transformation schedules",
    "AsyncCogniteClient.transformations.schedules.retrieve_multiple": "Retrieve multiple transformation schedules",
    "AsyncCogniteClient.transformations.schedules.update": "Update transformation schedules",
    "AsyncCogniteClient.transformations.notifications.create": "Create transformation notifications",
    "AsyncCogniteClient.transformations.notifications.delete": "Delete transformation notifications",
    "AsyncCogniteClient.transformations.notifications.list": "List transformation notifications",
    "AsyncCogniteClient.transformations.jobs.list": "List transformation jobs",
    "AsyncCogniteClient.transformations.jobs.retrieve": "Retrieve transformation jobs",
    "AsyncCogniteClient.transformations.jobs.retrieve_multiple": "Retrieve transformation jobs",
    "AsyncCogniteClient.transformations.schema.retrieve": "Get transformation schema",
    "AsyncCogniteClient.functions.call": "Call function",
    "AsyncCogniteClient.functions.create": "Create function",
    "AsyncCogniteClient.functions.delete": "Delete function",
    "AsyncCogniteClient.functions.list": "List functions",
    "AsyncCogniteClient.functions.retrieve": "Retrieve function",
    "AsyncCogniteClient.functions.retrieve_multiple": "Retrieve multiple functions",
    "AsyncCogniteClient.functions.calls.get_logs": "Retrieve function call logs",
    "AsyncCogniteClient.functions.calls.get_response": "Retrieve function call response",
    "AsyncCogniteClient.functions.calls.list": "List function calls",
    "AsyncCogniteClient.functions.calls.retrieve": "Retrieve function call",
    "AsyncCogniteClient.functions.schedules.create": "Create function schedule",
    "AsyncCogniteClient.functions.schedules.delete": "Delete function schedule",
    "AsyncCogniteClient.functions.schedules.list": "List function schedules",
    "AsyncCogniteClient.functions.schedules.retrieve": "Retrieve function schedule",
    "AsyncCogniteClient.functions.schedules.get_input_data": "Get function schedule input data",
    "AsyncCogniteClient.workflows.delete": "Delete Workflows",
    "AsyncCogniteClient.workflows.list": "List Workflows",
    "AsyncCogniteClient.workflows.retrieve": "Retrieve Workflows",
    "AsyncCogniteClient.workflows.upsert": "Upsert Workflows",
    "AsyncCogniteClient.workflows.versions.delete": "Delete Workflow Versions",
    "AsyncCogniteClient.workflows.versions.list": "List Workflow Versions",
    "AsyncCogniteClient.workflows.versions.retrieve": "Retrieve Workflow Versions",
    "AsyncCogniteClient.workflows.versions.upsert": "Upsert Workflows",
    "AsyncCogniteClient.workflows.executions.cancel": "Cancel Workflow Execution",
    "AsyncCogniteClient.workflows.executions.list": "List Workflow Executions",
    "AsyncCogniteClient.workflows.executions.retrieve_detailed": "Retrieve detailed Workflow Execution",
    "AsyncCogniteClient.workflows.executions.retry": "Retry Workflow Execution",
    "AsyncCogniteClient.workflows.executions.run": "Run Workflow Execution",
    "AsyncCogniteClient.workflows.tasks.update": "Update status of async Task",
    "AsyncCogniteClient.workflows.triggers.delete": "Delete Triggers",
    "AsyncCogniteClient.workflows.triggers.list": "List Triggers",
    "AsyncCogniteClient.workflows.triggers.list_runs": "List runs for a Trigger",
    "AsyncCogniteClient.workflows.triggers.pause": "Pause Trigger",
    "AsyncCogniteClient.workflows.triggers.resume": "Resume Trigger",
    "AsyncCogniteClient.workflows.triggers.upsert": "Upsert Trigger",
    "AsyncCogniteClient.simulators.list": "List simulators",
    "AsyncCogniteClient.simulators.integrations.delete": "Delete simulator integration",
    "AsyncCogniteClient.simulators.integrations.list": "List simulator integrations",
    "AsyncCogniteClient.simulators.models.create": "Create simulator models",
    "AsyncCogniteClient.simulators.models.delete": "Delete simulator models",
    "AsyncCogniteClient.simulators.models.list": "List simulator models",
    "AsyncCogniteClient.simulators.models.retrieve": "Retrieve simulator models",
    "AsyncCogniteClient.simulators.models.update": "Update simulator models",
    "AsyncCogniteClient.simulators.models.revisions.create": "Create simulator model revisions",
    "AsyncCogniteClient.simulators.models.revisions.list": "List simulator model revisions",
    "AsyncCogniteClient.simulators.models.revisions.retrieve": "Retrieve simulator model revisions",
    "AsyncCogniteClient.simulators.models.revisions.retrieve_data": "Retrieve simulator model revisions data",
    "AsyncCogniteClient.simulators.routines.create": "Create simulator routines",
    "AsyncCogniteClient.simulators.routines.delete": "Delete simulator routines",
    "AsyncCogniteClient.simulators.routines.list": "List simulator routines",
    "AsyncCogniteClient.simulators.routines.run": "Run simulator routines",
    "AsyncCogniteClient.simulators.routines.revisions.create": "Create simulator routine revisions",
    "AsyncCogniteClient.simulators.routines.revisions.list": "List simulator routine revisions",
    "AsyncCogniteClient.simulators.routines.revisions.retrieve": "Retrieve simulator routine revisions",
    "AsyncCogniteClient.simulators.runs.create": "Create simulation runs",
    "AsyncCogniteClient.simulators.runs.list": "List simulation runs",
    "AsyncCogniteClient.simulators.runs.list_run_data": "List simulation run data",
    "AsyncCogniteClient.simulators.runs.retrieve": "Retrieve simulation runs",
    "AsyncCogniteClient.simulators.logs.retrieve": "Retrieve simulator logs",
    "AsyncCogniteClient.geospatial.aggregate_features": "Aggregate features",
    "AsyncCogniteClient.geospatial.compute": "Compute",
    "AsyncCogniteClient.geospatial.create_features": "Create features",
    "AsyncCogniteClient.geospatial.create_feature_types": "Create feature types",
    "AsyncCogniteClient.geospatial.delete_features": "Delete features",
    "AsyncCogniteClient.geospatial.delete_feature_types": "Delete feature types",
    "AsyncCogniteClient.geospatial.get_coordinate_reference_systems": "Get coordinate reference systems",
    "AsyncCogniteClient.geospatial.get_raster": "Get raster data",
    "AsyncCogniteClient.geospatial.list_coordinate_reference_systems": "List coordinate reference systems",
    "AsyncCogniteClient.geospatial.list_features": "List features",
    "AsyncCogniteClient.geospatial.list_feature_types": "List feature types",
    "AsyncCogniteClient.geospatial.put_raster": "Put raster data",
    "AsyncCogniteClient.geospatial.retrieve_features": "Retrieve features",
    "AsyncCogniteClient.geospatial.retrieve_feature_types": "Retrieve feature types",
    "AsyncCogniteClient.geospatial.search_features": "Search features",
    "AsyncCogniteClient.geospatial.stream_features": "Stream features",
    "AsyncCogniteClient.geospatial.update_features": "Update features",
    "AsyncCogniteClient.geospatial.update_feature_types": "Update feature types",
    "AsyncCogniteClient.units.from_alias": "Look up Unit from alias",
    "AsyncCogniteClient.units.list": "List Units",
    "AsyncCogniteClient.units.retrieve": "Retrieve Unit",
    "AsyncCogniteClient.units.systems.list": "List Unit System",
    "AsyncCogniteClient.hosted_extractors.sources.create": "Create new source",
    "AsyncCogniteClient.hosted_extractors.sources.delete": "Delete source",
    "AsyncCogniteClient.hosted_extractors.sources.list": "List sources",
    "AsyncCogniteClient.hosted_extractors.sources.retrieve": "Retrieve sources",
    "AsyncCogniteClient.hosted_extractors.sources.update": "Update sources",
    "AsyncCogniteClient.hosted_extractors.jobs.create": "Create new job",
    "AsyncCogniteClient.hosted_extractors.jobs.delete": "Delete job",
    "AsyncCogniteClient.hosted_extractors.jobs.list": "List jobs",
    "AsyncCogniteClient.hosted_extractors.jobs.list_logs": "List job logs",
    "AsyncCogniteClient.hosted_extractors.jobs.list_metrics": "List job metrics",
    "AsyncCogniteClient.hosted_extractors.jobs.retrieve": "Retrieve jobs",
    "AsyncCogniteClient.hosted_extractors.jobs.update": "Update jobs",
    "AsyncCogniteClient.hosted_extractors.destinations.create": "Create new destinations",
    "AsyncCogniteClient.hosted_extractors.destinations.delete": "Delete destinations",
    "AsyncCogniteClient.hosted_extractors.destinations.list": "List destinations",
    "AsyncCogniteClient.hosted_extractors.destinations.retrieve": "Retrieve destinations",
    "AsyncCogniteClient.hosted_extractors.destinations.update": "Update destinations",
    "AsyncCogniteClient.hosted_extractors.mappings.create": "Create new mappings",
    "AsyncCogniteClient.hosted_extractors.mappings.delete": "Delete mappings",
    "AsyncCogniteClient.hosted_extractors.mappings.list": "List mappings",
    "AsyncCogniteClient.hosted_extractors.mappings.retrieve": "Retrieve mappings",
    "AsyncCogniteClient.hosted_extractors.mappings.update": "Update mappings",
    "AsyncCogniteClient.postgres_gateway.users.create": "Create Postgres Gateway Users",
    "AsyncCogniteClient.postgres_gateway.users.delete": "Delete Postgres Gateway Users",
    "AsyncCogniteClient.postgres_gateway.users.list": "List Postgres Gateway Users",
    "AsyncCogniteClient.postgres_gateway.users.retrieve": "Retrieve Postgres Gateway Users",
    "AsyncCogniteClient.postgres_gateway.users.update": "Update Postgres Gateway Users",
    "AsyncCogniteClient.postgres_gateway.tables.create": "Create Postgres Gateway Tables",
    "AsyncCogniteClient.postgres_gateway.tables.delete": "Delete Postgres Gateway Tables",
    "AsyncCogniteClient.postgres_gateway.tables.list": "List Postgres Gateway Tables",
    "AsyncCogniteClient.postgres_gateway.tables.retrieve": "Retrieve Postgres Gateway Tables",
    "AsyncCogniteClient.annotations.create": "Create an annotation",
    "AsyncCogniteClient.annotations.delete": "Delete annotations",
    "AsyncCogniteClient.annotations.list": "List annotation",
    "AsyncCogniteClient.annotations.update": "Update annotations",
    "AsyncCogniteClient.annotations.retrieve": "Retrieve an annotation by id",
    "AsyncCogniteClient.annotations.retrieve_multiple": "Retrieve multiple annotations by id",
    "AsyncCogniteClient.annotations.suggest": "Suggest an annotation",
    "AsyncCogniteClient.data_sets.aggregate_count": "Aggregate data sets",
    "AsyncCogniteClient.data_sets.create": "Create data sets",
    "AsyncCogniteClient.data_sets.list": "List data sets",
    "AsyncCogniteClient.data_sets.retrieve": "Retrieve a data set by id",
    "AsyncCogniteClient.data_sets.retrieve_multiple": "Retrieve multiple data sets by id",
    "AsyncCogniteClient.data_sets.update": "Update data sets",
    "AsyncCogniteClient.labels.create": "Create a label",
    "AsyncCogniteClient.labels.delete": "Delete labels",
    "AsyncCogniteClient.labels.list": "List labels",
    "AsyncCogniteClient.labels.retrieve": "Retrieve labels",
    "AsyncCogniteClient.relationships.create": "Create a relationship",
    "AsyncCogniteClient.relationships.delete": "Delete relationships",
    "AsyncCogniteClient.relationships.list": "List relationships",
    "AsyncCogniteClient.relationships.retrieve": "Retrieve a relationship by external id",
    "AsyncCogniteClient.relationships.retrieve_multiple": "Retrieve multiple relationships by external id",
    "AsyncCogniteClient.relationships.update": "Update relationships",
    "AsyncCogniteClient.relationships.upsert": "Upsert relationships",
    "AsyncCogniteClient.limits.list": "List",
    "AsyncCogniteClient.limits.retrieve": "Retrieve",
}
