environment:
  project: python-sdk-test-prod
  validation-type: prod
  selected:
  - modules/

variables:
  modules:
    read_write_group_source_id: 409f29f3-7e1b-461a-add1-1184d539b623
    readwrite_group_name: integration-test-runner
    #
    readonly_group_name: contributor
    readonly_group_source_id: 4521b63c-b914-44fe-9f86-f42b17fcb6c1
