---
name: Setup Python and install dependencies

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: false
        default: "3.8"
      extras:
        type: string
        required: false
        default: ""

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Set up cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-python-${{ inputs.python_version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip poetry
          poetry config virtualenvs.create false
          poetry install ${{ inputs.extras }}
