---
name: release

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup

      - name: Build package
        run: poetry build

      - name: Release to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --skip-existing --disable-progress-bar --verbose dist/*

      # TODO: Make this work again
      # - name: Push code snippets to service-contracts
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: sh ./scripts/deploy_code_snippets.sh || echo 'PR failed. There is probably
      #     nothing to commit'
